apiVersion: apps/v1
kind: Deployment
metadata:
    name: barramento-de-eventos-deployment
spec:
    replicas: 1
    selector:
        matchLabels:
            app: barramento-de-eventos
    template:
        metadata:
            labels:
                app: barramento-de-eventos
        spec:
            containers:
                - name: barramento-de-eventos
                  image: barramento-de-eventos
                  imagePullPolicy: IfNotPresent
                  ports:
                  - containerPort: 10000
---
apiVersion: v1
kind: Service
metadata:
 name: be-service
spec:
 selector:
    app: barramento-de-eventos
 ports:
    - protocol: TCP
      port: 10000
      targetPort: 10000