#deployments vem de apps/v1
apiVersion: apps/v1
#tipo
kind: Deployment
metadata:
    #nome do deployment
    name: hlb-deployment
spec:
    #quantas cópias
    replicas: 1
    #para especificar o rótulo
    selector:
        matchLabels:
            #rótulo, app não tem nada de especial, pode ser qq coisa
            #Deployment vai selecionar todo Pod que tiver esse rótulo
            app: hlb
    #modelo que vai ser usado para construção dos Pods
    template:
        metadata:
            labels:
                #os Pods terão esse rótulo, assim,
                #serão selecionados por esse deployment
                app: hlb
        spec:
            containers:
                - name: hlb
                  image: hlb/mss_hopital_crud
                - name: hlb
                  image: mss_hospital_analyzer